/*****************************************************************************
 * File generated by HDevelop Version 18.11
 *
 * Do not modify!
 *****************************************************************************/

using System;
using System.IO;
using HalconDotNet;


/*
 * If you use this class in your program, you have to 
 * link against hdevenginedotnet.dll and halcondotnet.dll.
 * The Dlls are located in ${HALCONROOT}/bin/dotnet[20|35].
 *
 * The wrapped .hdev or .hdpl files have to be located in the folder
 * that is specified in the static ResourcePath property of 
 * Mul_MultiThread_Test. 
 * By default, ResourcePath is ${binary_dir}/res_Mul_MultiThread_Test.
 *
 * It is recommended to compile an assembly from this file using
 * the generated CMakeLists.txt.
 */

namespace LT_Testing
{
  public static class Mul_MultiThread_Test
  {

    public static void Find_Data_Code2D_Max_Recognition(
        HObject Image,
        HObject ROI_FindCode,
        out HObject ImageReduced,
        out HObject SymbolXLDs,
        HTuple DataCodeHandle,
        HTuple number_code_to_find,
        out HTuple ResultHandles,
        out HTuple DecodedDataStrings)
    {     
      AddResourcePathToProcedurePath();
      using (HDevProcedureCall call = _Find_Data_Code2D_Max_Recognition.Value.CreateCall())
      {
        SetParameter(call,"Image",Image);
        SetParameter(call,"ROI_FindCode",ROI_FindCode);
        SetParameter(call,"DataCodeHandle",DataCodeHandle);
        SetParameter(call,"number_code_to_find",number_code_to_find);
        call.Execute();
        ImageReduced = GetParameterHObject(call,"ImageReduced");
        SymbolXLDs = GetParameterHObject(call,"SymbolXLDs");
        ResultHandles = GetParameterHTuple(call,"ResultHandles");
        DecodedDataStrings = GetParameterHTuple(call,"DecodedDataStrings");
      }
    }

    public static void Init_Data_Code2D_Max(
        out HTuple DataCodeHandle)
    {     
      AddResourcePathToProcedurePath();
      using (HDevProcedureCall call = _Init_Data_Code2D_Max.Value.CreateCall())
      {
        call.Execute();
        DataCodeHandle = GetParameterHTuple(call,"DataCodeHandle");
      }
    }

    public static void Proc_Mul_Testing_MultiThread(
        HTuple NumberInput1,
        HTuple NumberInput2,
        out HTuple NumberOutput)
    {     
      AddResourcePathToProcedurePath();
      using (HDevProcedureCall call = _Proc_Mul_Testing_MultiThread.Value.CreateCall())
      {
        SetParameter(call,"NumberInput1",NumberInput1);
        SetParameter(call,"NumberInput2",NumberInput2);
        call.Execute();
        NumberOutput = GetParameterHTuple(call,"NumberOutput");
      }
    }


    /****************************************************************************
    * ResourcePath
    *****************************************************************************
    * Use ResourcePath in your application to specify the location of the 
    * HDevelop script or procedure library.
    *****************************************************************************/
    public static string ResourcePath
    {
      get
      {
        return _resource_path;
      }
      set
      {
        lock(_procedure_path_lock)
        {
          _procedure_path_initialized = false;
        }
        _resource_path = value;
      }
    }

#region Implementation details

    /* Implementation details of the wrapper class.
     * You do not have to use these functions ever.
     */

    private static bool _procedure_path_initialized = false;
    private static object _procedure_path_lock = new object();

    private static string _resource_path = "./Mul_MultiThread_Test/res_Mul_MultiThread_Test";

    private static Lazy<HDevProgram> _Program
            = new Lazy<HDevProgram>(() => new HDevProgram(Path.Combine(Mul_MultiThread_Test.ResourcePath, "TEST.hdev")));
    private static Lazy<HDevProcedure> _Find_Data_Code2D_Max_Recognition
            = new Lazy<HDevProcedure>(() => new HDevProcedure(_Program.Value, "Find_Data_Code2D_Max_Recognition"));
    private static Lazy<HDevProcedure> _Init_Data_Code2D_Max
            = new Lazy<HDevProcedure>(() => new HDevProcedure(_Program.Value, "Init_Data_Code2D_Max"));
    private static Lazy<HDevProcedure> _Proc_Mul_Testing_MultiThread
            = new Lazy<HDevProcedure>(() => new HDevProcedure(_Program.Value, "Proc_Mul_Testing_MultiThread"));
        
    private static HTuple GetParameterHTuple(HDevProcedureCall call, string name)
    {
      return call.GetOutputCtrlParamTuple(name);
    }

    private static HObject GetParameterHObject(HDevProcedureCall call, string name)
    {
      return call.GetOutputIconicParamObject(name);
    }

    private static HTupleVector GetParameterHTupleVector(HDevProcedureCall call, string name)
    {
      return call.GetOutputCtrlParamVector(name);
    }

    private static HObjectVector GetParameterHObjectVector(HDevProcedureCall call, string name)
    {
      return call.GetOutputIconicParamVector(name);
    }

    private static void SetParameter(HDevProcedureCall call, string name, HTuple tuple)
    {
      call.SetInputCtrlParamTuple(name,tuple);
    }

    private static void SetParameter(HDevProcedureCall call, string name, HObject obj)
    {
      call.SetInputIconicParamObject(name,obj);
    }

    private static void SetParameter(HDevProcedureCall call, string name, HTupleVector vector)
    {
      call.SetInputCtrlParamVector(name,vector);
    }

    private static void SetParameter(HDevProcedureCall call, string name, HObjectVector vector)
    {
      call.SetInputIconicParamVector(name,vector);
    }

    private static void AddResourcePathToProcedurePath() 
    {
      lock(_procedure_path_lock)
      {
        if(!_procedure_path_initialized)
        {
          new HDevEngine().AddProcedurePath(ResourcePath);
          _procedure_path_initialized = true;
        }
      }
    }

#endregion

}
}